### PR TITLE
Mingw-w64 support

### PR DESCRIPTION
**Pull request by Alexpux**
1. Add support building with Mingw-w64 GCC
2. Fix different warnings

### CODE REVIEW

**Comment by JakubMelka** [comment]
Hello, sorry, I do not get email notification of this pull request. I will have look at it, but one important note - it is required to sign CLA (contributor license agreement) before contribution to this project can be accepted.

**Comment by Alexpux** [comment]
@JakubMelka where to send signed CLA?

**Comment by JakubMelka** [comment]
Please, fill CLA by written hand (unfilled CLA is in the repository), then scan it, and please send scanned document to Mgr.Jakub.Melka@gmail.com, thank you!

**Comment by Alexpux** [comment]
Okay

**Comment by Alexpux** [comment]
@JakubMelka I send CLA by email

**Comment by Alexpux** [comment]
there are a lot of conflicts now

**Comment by JakubMelka** [comment]
Hello, yes, I was fixing Qbs build on windows/linux and on MSVC/Clang/Mingw. Could you please carefully rebase and squash the commits into one? Thank you.

And one more note: Linux build with Qbs should work now.

**Comment by Alexpux** [comment]
@JakubMelka done in https://github.com/JakubMelka/PDF4QT/pull/11

**Pull request closed without merging**
